### ISSUE TITLE
breaking with defaults due to lack of setup file

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/requirements-builder#46]
``` python
requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt
Traceback (most recent call last):
  File "/Users/ppanero/.virtualenvs/test-reqs-build/bin/requirements-builder", line 8, in <module>
    sys.exit(cli())
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ppanero/.virtualenvs/test-reqs-build/lib/python3.6/site-packages/requirements_builder/cli.py", line 73, in cli
    setup_cfg = file.open(cfg, 'r')
NameError: name 'file' is not defined
```

Solution by @slint here:
https://github.com/inveniosoftware/requirements-builder/commit/d6297774d11e521687080bb5b4dc2355d902a103#r39419049

**Comment by ppanero** [comment]
closed by https://github.com/inveniosoftware/requirements-builder/pull/47
